### ISSUE TITLE
1.1.1 update broke use with browserify

### ISSUE THREAD

**Issue by auralia** [hughsk/vinyl-source-stream#25]
The following gulp code:
```
    return browserify({
                          debug: true,
                          entries: "src/ts/main.ts",
                          extensions: [".ts"]
                      })
        .plugin(tsify)
        .bundle()
        .on("error", function(err) {
            console.error(err.message);
            this.on("end", function() {
                process.exit(1)
            });
        })
        .pipe(source("bundle.js"))
        .pipe(buffer())
        .pipe(sourcemaps.init({loadMaps: true}))
        .pipe(uglify())
        .pipe(sourcemaps.write({includeContent: false, sourceRoot: "../../"}))
        .pipe(gulp.dest("build/js"));
```
no longer works with version 1.1.1 of vinyl-source-stream.

I now get the following error:
```
D:\nstg-web\node_modules\cloneable-readable\index.js:38
    throw new Error('already started')
    ^

Error: already started
    at Cloneable.clone (D:\nstg-web\node_modules\cloneable-readable\index.js:38:11)
    at File.clone (D:\nstg-web\node_modules\vinyl-source-stream\node_modules\vinyl\index.js:117:30)
    at BufferList._callback (D:\nstg-web\node_modules\vinyl-buffer\index.js:18:19)
    at BufferList.end (D:\nstg-web\node_modules\bl\bl.js:83:10)
    at Cloneable.onend (D:\nstg-web\node_modules\readable-stream\lib\_stream_readable.js:570:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at Cloneable.emit (events.js:208:7)
    at endReadableNT (D:\nstg-web\node_modules\readable-stream\lib\_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

It looks like I'm not the only person who's having this problem: https://translate.google.ca/translate?hl=en&sl=ja&u=https://qiita.com/hideo666nabe/items/a18b45d132dc8aef3327&prev=search

**Comment by phated** [comment]
@auralia it looks like the problem is with vinyl-buffer, not this module.

**Comment by phated** [comment]
Yep, there's no reason that vinyl-buffer should be cloning the file.  I'll submit a patch over there.

**Comment by phated** [comment]
I've submitted a PR to vinyl-buffer so we're just waiting on that.

**Comment by phated** [comment]
@auralia I've just reverted the change in 1.1.2 patch and cut a new major (2.0.0) release with the vinyl version update.  I'm also going to get vinyl-buffer upgraded shortly.

Thanks for bringing this to my attention.

**Comment by auralia** [comment]
Thanks for the quick response time!
